version: "3.8"

services:
  postgres: 
    image: postgres:${POSTGRES_VERSION}
    container_name: culture-postgres
    restart: on-failure
    hostname: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - culture_postgresql_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.general
      - ./env/.postgres

volumes:
  culture_postgresql_data: