version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgresql_value:/var/lib/postgresql/data/
    env_file:
      - ./infra/.env.example/.postgres

volumes:
  postgresql_value: