version: "3.8"

services:
  postgres: 
    image: 'postgres:${POSTGRES_VERSION}'
    restart: always
    container_name: postgres
    environment:
      DB_NAME: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    expose: 
      - ${POSTGRES_PORT}
    volumes:
      - postgresql_value:/var/lib/postgresql/data/

volumes:
  postgresql_value: