# Generated by Django 3.2 on 2023-08-29 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='Обложка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес начала')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('how_to_get', models.TextField(blank=True, null=True, verbose_name='Как добраться')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('photo', 'Фото'), ('reflection', 'Рефлексия'), ('quiz', 'Квиз'), ('continue_button', 'Кнопки')], max_length=20, verbose_name='Тип шага')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текстовое содержимое')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Фотография')),
                ('delay_after_display', models.IntegerField(blank=True, null=True, verbose_name='Задержка после показа')),
            ],
            options={
                'verbose_name': 'Шаг',
                'verbose_name_plural': 'Шаги',
                'ordering': ('-type',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('interests', models.CharField(blank=True, max_length=255, null=True, verbose_name='Интересы')),
            ],
        ),
        migrations.CreateModel(
            name='StageStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_priority', models.IntegerField(verbose_name='Приоритет шага')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.stage', verbose_name='Этап')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.step', verbose_name='Шаг')),
            ],
            options={
                'ordering': ('step_priority',),
            },
        ),
        migrations.CreateModel(
            name='RouteStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_priority', models.IntegerField(verbose_name='Приоритет этапа')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.route', verbose_name='Маршрут')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.stage', verbose_name='Этап')),
            ],
            options={
                'ordering': ('stage_priority',),
            },
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания рефлексии')),
                ('question', models.TextField(verbose_name='Вопрос для рефлексии')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Текстовое содержимое рефлексии')),
                ('voice', models.CharField(blank=True, max_length=255, null=True, verbose_name='Аудиофайл рефлексии')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.route', verbose_name='Маршрут')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.stage', verbose_name='Этап')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Оценка маршрута пользователем')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.route', verbose_name='Маршрут')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.stage', verbose_name='Этап')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.user', verbose_name='Пользователь')),
            ],
        ),
    ]
