# Generated by Django 3.2 on 2023-08-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0002_change_int_to_bigint_for_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='type',
            field=models.CharField(choices=[('text', 'Текст'), ('photo', 'Фото'), ('reflection', 'Рефлексия'), ('quiz', 'Квиз'), ('continue_button', 'Кнопки')], max_length=20, verbose_name='Тип шага'),
        ),
    ]
