"""empty message

Revision ID: 2c68d3b5850e
Revises:
Create Date: 2023-08-30 20:23:11.937196

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2c68d3b5850e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('culture_route',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('culture_stage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('how_to_get', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('culture_step',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('delay_after_display', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('culture_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('hobbies', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('culture_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['culture_route.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['culture_stage.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['culture_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('culture_reflection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('voice', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['culture_route.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['culture_stage.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['culture_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('culture_routestage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('stage_priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['culture_route.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['culture_stage.id'], ),
    sa.PrimaryKeyConstraint('id', 'route_id', 'stage_id')
    )
    op.create_table('culture_stagestep',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('step_priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['culture_stage.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['culture_step.id'], ),
    sa.PrimaryKeyConstraint('id', 'stage_id', 'step_id', 'step_priority')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('culture_stagestep')
    op.drop_table('culture_routestage')
    op.drop_table('culture_reflection')
    op.drop_table('culture_progress')
    op.drop_table('culture_user')
    op.drop_table('culture_step')
    op.drop_table('culture_stage')
    op.drop_table('culture_route')
    # ### end Alembic commands ###
