"""empty message

Revision ID: 8d35eda3e51c
Revises: 2c68d3b5850e
Create Date: 2023-10-02 23:32:54.140300

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d35eda3e51c'
down_revision: Union[str, None] = '2c68d3b5850e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('culture_survey',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('progress_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('most_memorable', sa.Text(), nullable=True),
    sa.Column('emotions', sa.Text(), nullable=True),
    sa.Column('proposal', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['progress_id'], ['culture_progress.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('culture_survey')
    # ### end Alembic commands ###
