name: Tests

on:

  push:
    branches: [ "feature/workflows_for_develop" ]

  workflow_dispatch:

jobs:
    tests:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12
      - name: Install dependencis
        run: |
          pip install poetry
          poetry install
          poetry shell
          poetry add flake8
      - name: Test with flake8
        run: |
          # запуск проверки проекта по flake8
          python3 -m flake8
